/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderType = IDL.Variant({
  'Print' : IDL.Null,
  'Custom' : IDL.Null,
  'Digital' : IDL.Null,
});
export const AddOrderArgs = IDL.Record({
  'customerName' : IDL.Text,
  'dueDate' : IDL.Text,
  'orderType' : OrderType,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Float64,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'Delivered' : IDL.Null,
  'Ready' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'dueDate' : IDL.Text,
  'isPaid' : IDL.Bool,
  'orderType' : OrderType,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Float64,
});
export const AddQuotationArgs = IDL.Record({
  'customerName' : IDL.Text,
  'orderType' : OrderType,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'phoneNumber' : IDL.Text,
});
export const QuotationId = IDL.Nat;
export const Quotation = IDL.Record({
  'id' : QuotationId,
  'customerName' : IDL.Text,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
  'phoneNumber' : IDL.Text,
  'totalPrice' : IDL.Float64,
});
export const DailyRevenueResult = IDL.Record({
  'revenue' : IDL.Float64,
  'date' : IDL.Text,
  'ordersCount' : IDL.Nat,
});
export const MonthlyRevenueResult = IDL.Record({
  'month' : IDL.Nat,
  'revenue' : IDL.Float64,
  'year' : IDL.Nat,
  'ordersCount' : IDL.Nat,
});
export const PendingPaymentsInfo = IDL.Record({
  'totalUnpaidAmount' : IDL.Float64,
  'totalUnpaidOrders' : IDL.Nat,
});
export const UpdateOrderArgs = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'dueDate' : IDL.Text,
  'isPaid' : IDL.Bool,
  'orderType' : OrderType,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'phoneNumber' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addOrder' : IDL.Func([AddOrderArgs], [Order], []),
  'addQuotation' : IDL.Func([AddQuotationArgs], [Quotation], []),
  'convertQuotationToOrder' : IDL.Func(
      [QuotationId, IDL.Text, IDL.Text],
      [IDL.Opt(Order)],
      [],
    ),
  'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
  'deleteQuotation' : IDL.Func([QuotationId], [IDL.Bool], []),
  'getDailyRevenue' : IDL.Func([IDL.Text], [DailyRevenueResult], ['query']),
  'getMonthlyRevenue' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyRevenueResult],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersCompletedCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingPaymentsInfo' : IDL.Func([], [PendingPaymentsInfo], ['query']),
  'getQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
  'updateOrder' : IDL.Func([UpdateOrderArgs], [IDL.Bool], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderType = IDL.Variant({
    'Print' : IDL.Null,
    'Custom' : IDL.Null,
    'Digital' : IDL.Null,
  });
  const AddOrderArgs = IDL.Record({
    'customerName' : IDL.Text,
    'dueDate' : IDL.Text,
    'orderType' : OrderType,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Float64,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'Delivered' : IDL.Null,
    'Ready' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'createdAt' : Timestamp,
    'dueDate' : IDL.Text,
    'isPaid' : IDL.Bool,
    'orderType' : OrderType,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Float64,
  });
  const AddQuotationArgs = IDL.Record({
    'customerName' : IDL.Text,
    'orderType' : OrderType,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'phoneNumber' : IDL.Text,
  });
  const QuotationId = IDL.Nat;
  const Quotation = IDL.Record({
    'id' : QuotationId,
    'customerName' : IDL.Text,
    'createdAt' : Timestamp,
    'orderType' : OrderType,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
    'phoneNumber' : IDL.Text,
    'totalPrice' : IDL.Float64,
  });
  const DailyRevenueResult = IDL.Record({
    'revenue' : IDL.Float64,
    'date' : IDL.Text,
    'ordersCount' : IDL.Nat,
  });
  const MonthlyRevenueResult = IDL.Record({
    'month' : IDL.Nat,
    'revenue' : IDL.Float64,
    'year' : IDL.Nat,
    'ordersCount' : IDL.Nat,
  });
  const PendingPaymentsInfo = IDL.Record({
    'totalUnpaidAmount' : IDL.Float64,
    'totalUnpaidOrders' : IDL.Nat,
  });
  const UpdateOrderArgs = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'dueDate' : IDL.Text,
    'isPaid' : IDL.Bool,
    'orderType' : OrderType,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'phoneNumber' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addOrder' : IDL.Func([AddOrderArgs], [Order], []),
    'addQuotation' : IDL.Func([AddQuotationArgs], [Quotation], []),
    'convertQuotationToOrder' : IDL.Func(
        [QuotationId, IDL.Text, IDL.Text],
        [IDL.Opt(Order)],
        [],
      ),
    'deleteOrder' : IDL.Func([OrderId], [IDL.Bool], []),
    'deleteQuotation' : IDL.Func([QuotationId], [IDL.Bool], []),
    'getDailyRevenue' : IDL.Func([IDL.Text], [DailyRevenueResult], ['query']),
    'getMonthlyRevenue' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyRevenueResult],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersCompletedCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingPaymentsInfo' : IDL.Func([], [PendingPaymentsInfo], ['query']),
    'getQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
    'updateOrder' : IDL.Func([UpdateOrderArgs], [IDL.Bool], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };