/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddOrderArgs {
  'customerName' : string,
  'dueDate' : string,
  'orderType' : OrderType,
  'notes' : string,
  'quantity' : bigint,
  'phoneNumber' : string,
  'price' : number,
}
export interface AddQuotationArgs {
  'customerName' : string,
  'orderType' : OrderType,
  'quantity' : bigint,
  'unitPrice' : number,
  'phoneNumber' : string,
}
export interface DailyRevenueResult {
  'revenue' : number,
  'date' : string,
  'ordersCount' : bigint,
}
export interface MonthlyRevenueResult {
  'month' : bigint,
  'revenue' : number,
  'year' : bigint,
  'ordersCount' : bigint,
}
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'createdAt' : Timestamp,
  'dueDate' : string,
  'isPaid' : boolean,
  'orderType' : OrderType,
  'notes' : string,
  'quantity' : bigint,
  'phoneNumber' : string,
  'price' : number,
}
export type OrderId = bigint;
export type OrderStatus = { 'Delivered' : null } |
  { 'Ready' : null } |
  { 'Pending' : null };
export type OrderType = { 'Print' : null } |
  { 'Custom' : null } |
  { 'Digital' : null };
export interface PendingPaymentsInfo {
  'totalUnpaidAmount' : number,
  'totalUnpaidOrders' : bigint,
}
export interface Quotation {
  'id' : QuotationId,
  'customerName' : string,
  'createdAt' : Timestamp,
  'orderType' : OrderType,
  'quantity' : bigint,
  'unitPrice' : number,
  'phoneNumber' : string,
  'totalPrice' : number,
}
export type QuotationId = bigint;
export type Timestamp = bigint;
export interface UpdateOrderArgs {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'dueDate' : string,
  'isPaid' : boolean,
  'orderType' : OrderType,
  'notes' : string,
  'quantity' : bigint,
  'phoneNumber' : string,
  'price' : number,
}
export interface _SERVICE {
  'addOrder' : ActorMethod<[AddOrderArgs], Order>,
  'addQuotation' : ActorMethod<[AddQuotationArgs], Quotation>,
  'convertQuotationToOrder' : ActorMethod<
    [QuotationId, string, string],
    [] | [Order]
  >,
  'deleteOrder' : ActorMethod<[OrderId], boolean>,
  'deleteQuotation' : ActorMethod<[QuotationId], boolean>,
  'getDailyRevenue' : ActorMethod<[string], DailyRevenueResult>,
  'getMonthlyRevenue' : ActorMethod<[bigint, bigint], MonthlyRevenueResult>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersCompletedCount' : ActorMethod<[], bigint>,
  'getPendingPaymentsInfo' : ActorMethod<[], PendingPaymentsInfo>,
  'getQuotations' : ActorMethod<[], Array<Quotation>>,
  'updateOrder' : ActorMethod<[UpdateOrderArgs], boolean>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];