/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AddOrderArgs {
    customerName: string;
    dueDate: string;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}
export interface Quotation {
    id: QuotationId;
    customerName: string;
    createdAt: Timestamp;
    orderType: OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
    totalPrice: number;
}
export type Timestamp = bigint;
export interface PendingPaymentsInfo {
    totalUnpaidAmount: number;
    totalUnpaidOrders: bigint;
}
export type QuotationId = bigint;
export interface UpdateOrderArgs {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    dueDate: string;
    isPaid: boolean;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}
export interface MonthlyRevenueResult {
    month: bigint;
    revenue: number;
    year: bigint;
    ordersCount: bigint;
}
export interface AddQuotationArgs {
    customerName: string;
    orderType: OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
}
export interface DailyRevenueResult {
    revenue: number;
    date: string;
    ordersCount: bigint;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    createdAt: Timestamp;
    dueDate: string;
    isPaid: boolean;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}
export type OrderId = bigint;
export enum OrderStatus {
    Delivered = "Delivered",
    Ready = "Ready",
    Pending = "Pending"
}
export enum OrderType {
    Print = "Print",
    Custom = "Custom",
    Digital = "Digital"
}
export interface backendInterface {
    addOrder(args: AddOrderArgs): Promise<Order>;
    addQuotation(args: AddQuotationArgs): Promise<Quotation>;
    convertQuotationToOrder(quotationId: QuotationId, dueDate: string, notes: string): Promise<Order | null>;
    deleteOrder(id: OrderId): Promise<boolean>;
    deleteQuotation(id: QuotationId): Promise<boolean>;
    getDailyRevenue(date: string): Promise<DailyRevenueResult>;
    getMonthlyRevenue(year: bigint, month: bigint): Promise<MonthlyRevenueResult>;
    getOrder(id: OrderId): Promise<Order | null>;
    getOrders(): Promise<Array<Order>>;
    getOrdersCompletedCount(): Promise<bigint>;
    getPendingPaymentsInfo(): Promise<PendingPaymentsInfo>;
    getQuotations(): Promise<Array<Quotation>>;
    updateOrder(args: UpdateOrderArgs): Promise<boolean>;
    updateOrderStatus(id: OrderId, newStatus: OrderStatus): Promise<boolean>;
}
import type { AddOrderArgs as _AddOrderArgs, AddQuotationArgs as _AddQuotationArgs, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, OrderType as _OrderType, Quotation as _Quotation, QuotationId as _QuotationId, Timestamp as _Timestamp, UpdateOrderArgs as _UpdateOrderArgs } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addOrder(arg0: AddOrderArgs): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.addOrder(to_candid_AddOrderArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOrder(to_candid_AddOrderArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addQuotation(arg0: AddQuotationArgs): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuotation(to_candid_AddQuotationArgs_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Quotation_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuotation(to_candid_AddQuotationArgs_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Quotation_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async convertQuotationToOrder(arg0: QuotationId, arg1: string, arg2: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.convertQuotationToOrder(arg0, arg1, arg2);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertQuotationToOrder(arg0, arg1, arg2);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteOrder(arg0: OrderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOrder(arg0);
            return result;
        }
    }
    async deleteQuotation(arg0: QuotationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuotation(arg0);
            return result;
        }
    }
    async getDailyRevenue(arg0: string): Promise<DailyRevenueResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRevenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRevenue(arg0);
            return result;
        }
    }
    async getMonthlyRevenue(arg0: bigint, arg1: bigint): Promise<MonthlyRevenueResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyRevenue(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyRevenue(arg0, arg1);
            return result;
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersCompletedCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersCompletedCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersCompletedCount();
            return result;
        }
    }
    async getPendingPaymentsInfo(): Promise<PendingPaymentsInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPaymentsInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPaymentsInfo();
            return result;
        }
    }
    async getQuotations(): Promise<Array<Quotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotations();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotations();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrder(arg0: UpdateOrderArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrder(to_candid_UpdateOrderArgs_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrder(to_candid_UpdateOrderArgs_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_OrderStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Quotation_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Quotation): Quotation {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _QuotationId;
    customerName: string;
    createdAt: _Timestamp;
    orderType: _OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
    totalPrice: number;
}): {
    id: QuotationId;
    customerName: string;
    createdAt: Timestamp;
    orderType: OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
    totalPrice: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        createdAt: value.createdAt,
        orderType: from_candid_OrderType_n9(_uploadFile, _downloadFile, value.orderType),
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        phoneNumber: value.phoneNumber,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    createdAt: _Timestamp;
    dueDate: string;
    isPaid: boolean;
    orderType: _OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    createdAt: Timestamp;
    dueDate: string;
    isPaid: boolean;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n7(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        isPaid: value.isPaid,
        orderType: from_candid_OrderType_n9(_uploadFile, _downloadFile, value.orderType),
        notes: value.notes,
        quantity: value.quantity,
        phoneNumber: value.phoneNumber,
        price: value.price
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Print: null;
} | {
    Custom: null;
} | {
    Digital: null;
}): OrderType {
    return "Print" in value ? OrderType.Print : "Custom" in value ? OrderType.Custom : "Digital" in value ? OrderType.Digital : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Delivered: null;
} | {
    Ready: null;
} | {
    Pending: null;
}): OrderStatus {
    return "Delivered" in value ? OrderStatus.Delivered : "Ready" in value ? OrderStatus.Ready : "Pending" in value ? OrderStatus.Pending : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Quotation>): Array<Quotation> {
    return value.map((x)=>from_candid_Quotation_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AddOrderArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddOrderArgs): _AddOrderArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AddQuotationArgs_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddQuotationArgs): _AddQuotationArgs {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateOrderArgs_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateOrderArgs): _UpdateOrderArgs {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    orderType: OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
}): {
    customerName: string;
    orderType: _OrderType;
    quantity: bigint;
    unitPrice: number;
    phoneNumber: string;
} {
    return {
        customerName: value.customerName,
        orderType: to_candid_OrderType_n3(_uploadFile, _downloadFile, value.orderType),
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        phoneNumber: value.phoneNumber
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    dueDate: string;
    isPaid: boolean;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}): {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    dueDate: string;
    isPaid: boolean;
    orderType: _OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n20(_uploadFile, _downloadFile, value.status),
        dueDate: value.dueDate,
        isPaid: value.isPaid,
        orderType: to_candid_OrderType_n3(_uploadFile, _downloadFile, value.orderType),
        notes: value.notes,
        quantity: value.quantity,
        phoneNumber: value.phoneNumber,
        price: value.price
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    dueDate: string;
    orderType: OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
}): {
    customerName: string;
    dueDate: string;
    orderType: _OrderType;
    notes: string;
    quantity: bigint;
    phoneNumber: string;
    price: number;
} {
    return {
        customerName: value.customerName,
        dueDate: value.dueDate,
        orderType: to_candid_OrderType_n3(_uploadFile, _downloadFile, value.orderType),
        notes: value.notes,
        quantity: value.quantity,
        phoneNumber: value.phoneNumber,
        price: value.price
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    Delivered: null;
} | {
    Ready: null;
} | {
    Pending: null;
} {
    return value == OrderStatus.Delivered ? {
        Delivered: null
    } : value == OrderStatus.Ready ? {
        Ready: null
    } : value == OrderStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    Print: null;
} | {
    Custom: null;
} | {
    Digital: null;
} {
    return value == OrderType.Print ? {
        Print: null
    } : value == OrderType.Custom ? {
        Custom: null
    } : value == OrderType.Digital ? {
        Digital: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
